### ISSUE TITLE
 装备数据定义疑问

### ISSUE THREAD

**Issue by WatermelonRei** [gf-data-tools/gf-data-ch#3]
对比了equip.json与游戏中的数据，发现满强化校准的特殊人形装备的数据对不上，以回避为例：

id | dodge(json) | dodge(raw)
-- | -- | --
127 | 12 | 20
86 | 4 | 5
91 | 8 | 10
107 | -2 | -2
141 | 15 | 15
297 | -1 | -1
275 | 12 | 20
260 | 20 | 40
213 | 15 | 25
237 | 20 | 30
171 | 12 | 20
192 | 25 | 45
92 | 25 | 35
159 | 12 | 20
62 | 45 | 58

有些装备数据匹配，有的数据不同

以伤害为例：

id | pow(json) | pow(raw)
-- | -- | --
293 | 3 | 5
275 | 10 | 20
248 | 10 | 15
255 | 12 | 18
190 | 10 | 20
192 | -6 | -6
197 | -6 | -6
159 | 10 | 25
107 | -25 | -25
86 | 25 | 30
127 | 10 | 25
65 | -6 | -6
99 | 10 | 20

是因为数据没有及时更新还是因为存在内部算法或定义有差异？

**Comment by ZeroRin** [comment]
因为你的raw这列数据是错的。
以第一条为例，id127狐狸球,游戏内图鉴可以看到回避为12，与json列一致，与raw列不符。
![image](https://user-images.githubusercontent.com/14952735/232238137-1cd6919d-187b-499b-81ac-26e5618dc643.png)

**Comment by WatermelonRei** [comment]
RAW数据来源国服，官方调整了数据吗
![Screenshot_20230416_024751](https://user-images.githubusercontent.com/26793403/232248122-04abd65c-aee3-49d6-a530-066eee99f95d.png)

**Comment by WatermelonRei** [comment]
有疑问的数据都是我自己的账号里举例出来的，在配队时发现计算器给出的效能还有提升，研究了数据文件发现数据对不上

**Comment by ZeroRin** [comment]
+10数据你乘强化倍率啊
